spring.application.name=demo

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${PRODUCT_SERVICE_DB_URL}
spring.datasource.username=${PRODUCT_SERVICE_DB_USER}
spring.datasource.password=${PRODUCT_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
project.image = images/
server.port=${PRODUCT_SERVICE_PORT_NUMBER}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://USERSERVICE/.well-known/jwks.json
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:3030
spring.cloud.loadbalancer.ribbon.enabled=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/